"""Game model — one row per game session."""

import uuid
from datetime import datetime, timezone
from typing import List

from sqlalchemy import ARRAY, String
from sqlmodel import Column, Field, SQLModel

from app.enums.game_status import GameStatus


class Game(SQLModel, table=True):
    # UUID primary key — generated by the app, not the database
    uuid: str = Field(default_factory=lambda: str(uuid.uuid4()), primary_key=True)

    # The answer the player is trying to guess — never sent to the frontend
    secret_word: str = Field(max_length=5)

    # All guesses submitted so far — stored as a PostgreSQL ARRAY since SQLModel has no native list type
    guesses: List[str] = Field(default_factory=list, sa_column=Column(ARRAY(String)))

    # Number of guesses submitted (0–6)
    attempts: int = Field(default=0)

    # Game lifecycle state — active, won, or lost
    status: str = Field(default=GameStatus.ACTIVE)

    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc), index=True
    )
    updated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
